name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3
      - name: 配置引导镜像
        run: cp sample_user_config.json ds920p_user_config.json
      - name: 准备构建环境
        run: ./redpill_tool_chain.sh build ds920p-7.0.1-42218
      - name: 添加 jumkey.dtb !!!Create your own device tree binary!!!
        run: ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-dtb.json
      - name: 编译引导镜像
        run: ./redpill_tool_chain.sh auto ds920p-7.0.1-42218
      - name: 打包
        run: tar -cvf custom.tar *
      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v3
        with:
          name: dsm-ds920p-7.0.1-42218
          path: custom.tar
